name: RankQuests
author: Yukun
main: me.yukun.rankquests.RankQuests
version: 2.0.3
api-version: 1.13
softdepend: [ Factions, WorldGuard ]
description: >
  A plugin to make players complete a timed quest before they receive a rank.
commands:
  rankquest:
    description: Base command for RankQuests plugin.
    aliases: [ rankquest, rq, rquest ]